### ISSUE TITLE
[Bug] The page indicator doesn't work properly

### ISSUE THREAD

**Issue by minhnimble** [bigdreamer1610/SurveyApp-Swift#12]
## Issue

When tapping on the page indicator to open a specific page, the page indicator doesn't do anything. The user can only swipe left and right to go through the content and it is quite inconvenient.

At the same time, when users scrolling for more items (toward the last one), users can see new survey items but the page indicator's selected page went missing.

https://github.com/bigdreamer1610/SurveyApp-Swift/assets/70877098/7992f9d2-d11f-4559-85c1-bb745722b36e

## Expect

- The page indicator should be shown correctly regardless of the current page it is showing on the screen.
- Tapping on the page indicator should allow the user to navigate to the selected page.

**Comment by bigdreamer1610** [comment]
Fixed on #19

**Comment by bigdreamer1610** [comment]
Fixed on #22
