### ISSUE TITLE
[Bug] The user information is missing when starting the application without internet connection

### ISSUE THREAD

**Issue by minhnimble** [bigdreamer1610/SurveyApp-Swift#14]
## Issue

When starting the application with a previously logged in session and without a internet connection, the user information is gone when having the connection back.

https://github.com/bigdreamer1610/SurveyApp-Swift/assets/70877098/837c10c4-9114-48f2-925a-d2339dcf8493

## Expect

The user information should be refreshed and retrieved properly.

**Comment by bigdreamer1610** [comment]
Fixed on #21 

Details: 
- Add a NetworkObserver to observe internet connection
- Cache User Profile data 
- When internet goes active again, check if user profile data exists, else call get profile api to fetch data.
