### ISSUE TITLE
 Start of the code review process 👋

### ISSUE THREAD

**Issue by minhnimble** [bigdreamer1610/SurveyApp-Swift#9]
Hello Thuy 👋 , thank you for your effort on the code submission. I am Mike, Engineering Lead at Nimble, and I am happy to be the reviewer for our code review session.

During the review process, I would like to know more about your decisions, so I will create issues in some areas where there could be more improvements regarding your submission. Since solving every possible problem would take too long, I will prioritize the most important ones.

At the same time, please keep in mind that this is a bi-directional process, and I would love to hear back from you as well. Therefore, do not hesitate to ask questions or share your opinions about the implementation (if any) during the process.

We expect the code review process to be completed within 2-3 days. As a result, please make sure you are responsive during this process. If you need more time, please let us know as soon as possible so we can plan accordingly.

If we are aligned on any issue, and you would like to correct them, please address the issue using a proper git flow (creating a new branch, opening a Pull Request (PR) per issue, and merging the code when you are ready), and I will follow up on those fixes. Just so you know, you don't have to close any of my created issues after merging your PRs; I will help verify and close them for you once they pass. 😇

In the end, I do hope that you find the process enjoyable. Good luck and happy coding. 🤘

**Comment by bigdreamer1610** [comment]
Thank your Mike for being the reviewer for my submission. 

I'll follow along whenever a new issue is created. 

Wish you a great working week!

**Comment by minhnimble** [comment]
Hi, Thuy 👋

For your information, I just complete the 1st round of review now. Please go ahead and provide your feedback on all the proposed issues. Regarding the timeline, the target is to conclude everything by the end of this Friday, thus it would be best if you could address the issues before that time. If you have any further inquiry, please don't hesitate to communicate them here.

Have a great evening!

**Comment by bigdreamer1610** [comment]
I have left some answers on issues which do not require coding. Please check those issues again for me, thank you very much!

As for the rest, I'll work on them from tomorrow and notify you when I'm done.

**Comment by bigdreamer1610** [comment]
Good evening Mike, how are you doing today? 

I've updated answers for 6/9 issues, hope you'll have some time to go through them today and give me feedbacks if there're something else I should I work on more to improve them. 

As for the last 3 ones, I'll try to fix/update answers for as soon as I could in order to meet the deadline by the end of tomorrow. 

Regards, 
Thuy Nguyen

**Comment by minhnimble** [comment]
Good afternoon, Thuy  ☀️

As of this point, this code challenge review session has concluded, and you won't need to provide any more discussion or submission. About the next step, you will hear from our Talent Acquisition team about the decision in the upcoming days. 

Ultimately, it was nice collaborating with you on the code challenge and getting to know you. Thanks for your time, and I wish you all the best! 🍀
